/* Generated By:JJTree: Do not edit this line. ASTBinOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBinOp extends SimpleNode {
  public ASTBinOp(int id) {
    super(id);
  }

  public ASTBinOp(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75d6ecad0bebe104d8cc9ec3aa6508de (do not edit this line) */
