/* Generated By:JJTree: Do not edit this line. ASTGreaterThan.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreaterThan extends SimpleNode {
  public ASTGreaterThan(int id) {
    super(id);
  }

  public ASTGreaterThan(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d4e20414a913e3aab4ab64431b2f57eb (do not edit this line) */
