/* Generated By:JJTree: Do not edit this line. ASTGreaterOrEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreaterOrEqual extends SimpleNode {
  public ASTGreaterOrEqual(int id) {
    super(id);
  }

  public ASTGreaterOrEqual(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5da5f3edc9d66b26f28103dadec09460 (do not edit this line) */
