/* Generated By:JJTree: Do not edit this line. ASTLessOrEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessOrEqual extends SimpleNode {
  public ASTLessOrEqual(int id) {
    super(id);
  }

  public ASTLessOrEqual(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=172fddc48c42cede068991af251db960 (do not edit this line) */
