/* Generated By:JJTree: Do not edit this line. ASTStateBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStateBlock extends SimpleNode {
  public ASTStateBlock(int id) {
    super(id);
  }

  public ASTStateBlock(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=89014e583e1b0408b1d600b2e49a550e (do not edit this line) */
