/* Generated By:JavaCC: Do not edit this line. CCALTreeConstants.java Version 5.0 */
public interface CCALTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTCONST = 3;
  public int JJTFUNCLIST = 4;
  public int JJTFUNC = 5;
  public int JJTPARAMS = 6;
  public int JJTMAIN = 7;
  public int JJTTYPE = 8;
  public int JJTSTATEBLOCK = 9;
  public int JJTBINOP = 10;
  public int JJTADD = 11;
  public int JJTSUB = 12;
  public int JJTOR = 13;
  public int JJTAND = 14;
  public int JJTCOMPOP = 15;
  public int JJTEQUAL = 16;
  public int JJTNOTEQUAL = 17;
  public int JJTLESSTHAN = 18;
  public int JJTLESSOREQUAL = 19;
  public int JJTGREATERTHAN = 20;
  public int JJTGREATEROREQUAL = 21;
  public int JJTARGLIST = 22;
  public int JJTID = 23;
  public int JJTNUM = 24;
  public int JJTBOOL = 25;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Decl",
    "Const",
    "FuncList",
    "Func",
    "Params",
    "Main",
    "Type",
    "StateBlock",
    "BinOp",
    "Add",
    "Sub",
    "OR",
    "AND",
    "CompOp",
    "Equal",
    "NotEqual",
    "LessThan",
    "LessOrEqual",
    "GreaterThan",
    "GreaterOrEqual",
    "ArgList",
    "Id",
    "Num",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=2d945f88ae6b6677433796368d495e08 (do not edit this line) */
