/* Generated By:JJTree&JavaCC: Do not edit this line. CCALConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCALConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SEMI_COLON = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int EQUALS = 14;
  /** RegularExpression Id. */
  int LBR = 15;
  /** RegularExpression Id. */
  int RBR = 16;
  /** RegularExpression Id. */
  int PLUS_SIGN = 17;
  /** RegularExpression Id. */
  int MINUS_SIGN = 18;
  /** RegularExpression Id. */
  int TILDA = 19;
  /** RegularExpression Id. */
  int OR_SIGN = 20;
  /** RegularExpression Id. */
  int AND_SIGN = 21;
  /** RegularExpression Id. */
  int EQUAL_TO = 22;
  /** RegularExpression Id. */
  int NOT_EQUAL_TO = 23;
  /** RegularExpression Id. */
  int LESS_THAN = 24;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL = 25;
  /** RegularExpression Id. */
  int GREATER_THAN = 26;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL = 27;
  /** RegularExpression Id. */
  int VAR = 28;
  /** RegularExpression Id. */
  int CONST = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int INTEGER = 31;
  /** RegularExpression Id. */
  int BOOLEAN = 32;
  /** RegularExpression Id. */
  int VOID = 33;
  /** RegularExpression Id. */
  int MAIN = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int BEGIN = 40;
  /** RegularExpression Id. */
  int END = 41;
  /** RegularExpression Id. */
  int IS = 42;
  /** RegularExpression Id. */
  int SKIP_IT = 43;
  /** RegularExpression Id. */
  int NUMBER = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int ID = 46;
  /** RegularExpression Id. */
  int LETTER = 47;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"//\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"var\"",
    "\"const\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"is\"",
    "\"skip\"",
    "<NUMBER>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
  };

}
