/* Generated By:JavaCC: Do not edit this line. CCALVisitor.java Version 5.0 */
public interface CCALVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDecl node, Object data);
  public Object visit(ASTConst node, Object data);
  public Object visit(ASTFuncList node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTParams node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTStateBlock node, Object data);
  public Object visit(ASTBinOp node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTOR node, Object data);
  public Object visit(ASTAND node, Object data);
  public Object visit(ASTCompOp node, Object data);
  public Object visit(ASTEqual node, Object data);
  public Object visit(ASTNotEqual node, Object data);
  public Object visit(ASTLessThan node, Object data);
  public Object visit(ASTLessOrEqual node, Object data);
  public Object visit(ASTGreaterThan node, Object data);
  public Object visit(ASTGreaterOrEqual node, Object data);
  public Object visit(ASTArgList node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTBool node, Object data);
}
/* JavaCC - OriginalChecksum=48c1b24fa626547668585761c5b08cee (do not edit this line) */
